import process from 'node:process';
import { builtinModules } from 'node:module';
import type { BuildOptions } from 'esbuild';
import { at } from '../utils/directory-util.mjs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/kotaindah55/mainstream-icons
*/
`;

const dev = process.argv[2] === 'dev';

export default {
	banner: {
		js: banner,
	},
	entryPoints: [
		at('src/main.ts')
	],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'i18next',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: 'info',
	treeShaking: true,
	sourcemap: dev ? 'inline' : false,
	outfile: at('dist/main.js'),
	minify: !dev,
	tsconfig: at('tsconfig.json')
} as BuildOptions;